### PR TITLE
Integrated cart and payment together, fixed redirect button in cart, fixed server rendering

### PR DESCRIPTION
**Pull request by neenachcha**
Hi Guys, I was just Integrated cart and payment together, fixed redirect button in cart, fixed server rendering. But I ended up deleting unused comments, and fixing some spaces in many files. Good News, This version can render in 3001 & 3000. Moreover, when you reach the payment page, and back to cart, you can still see items in cart. 

Here are a few bug that I haven't solve.
1. From cart, you can go back to menu, but item in the cart doesn't persist yet.
2. From cart, button "back to restaurant" bring you to menu instead. I couldn't figure out why.

Here are the summary of changes in every file.
1. Payment.js & bill.js 
- update to get session_code from cookie
- update to get user_id from cookieData.username
- delete not use console log
- update error handler in initialize
2. Bill.js 
- update calculateBillSummary to work only if user_pick size is more than 0
3. payment redirection button 
- delete not use console log
4. component cart.js
- change div to stack
- delete not used function updateSummaryDatabase (already checked with tan)
- delete not used comment
5. component cart redirectionbutton.js
- move link outside button to be able to click the button not the link
- get rid of unused space and function
6. summary.js
- delete comment
7. fullMenu.js
- reorganize space
- fix error in setCart
- add useEffect after setCart to rerender after Cart changes, and to set cart in localstorage everytime cart changes. So back to cart can still see the item in cart.
8. component menu.js
- reorganize spaces, delete unneccessary comments
- move setting fullMenu local storage to this component. So that button back to menu, can come back to this menu again.
9. rest_pick.js
- In joinSearch, add userId param to url, so Tan can update userId when update group_cart database. Delete option params because it's not working.
10. In Navbar, displaymenuleft and right,
- update to use <Link> (according to grant this will make server side works), and it works!
- move copyright here, and make sure it's at the bottom screen on all pages.
- update logout to clear localstorage
- update logout to clear username and id set in the app.js state.
11. App.js
- add function navigateToLogin that will set state of username, userId, and verified back.
- Pass this functin to navbar, and use when logout.
12. src/index.js
- move copyright to navbar.js
13. database/index.js
- ipaddress that deploy database change
- update comment about using deployed database and local database
14. controller/authentication - logout
- update to clear cookie session_coode and orderSession
- update cookie splitsy to empty string and 0 instead. So it won't break front-end, when there is no splitsy cookie, at log out.
15. contrller/cart/index
- In cart.forEach update user_id to get user_id from jwtObj
16. controller/joinorder
- fixing spaces
17. controller/payment/index
- delete comment
18. controller/restaurant/index
- fix spaces
19. controller/sessions/index
- fix space
20. server/index
- organize code and spaces
21. server/routes.js
- delete not used function authentication

### CODE REVIEW

**Review by ayokanme — APPROVED** [review]

**Review by yfcheng1 — APPROVED** [review]
Great job Neen! Thank you!

**Review by ayokanme — APPROVED** [review]
Excellent work, Neen! Thanks for all the hard work. Really appreciate having you on the team.

**Review by tandha — COMMENTED** [review]
Great work, Neen, and thank you for the thorough walkthrough of changes you have made in the code!

**Review by tandha — APPROVED** [review]

**Review by denniswangcodes — APPROVED** [review]

**Review by grant350 — APPROVED** [review]
Looks great ready to merge

**Pull request merged**
